// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npnchypfnzalurwsafmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wbmNoeXBmbnphbHVyd3NhZm1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODg4ODgsImV4cCI6MjA2OTk2NDg4OH0.vBIjKurMDA1IsOoRHU3a-s_nEQVP0F_o_1GMziERtMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});